name: DurabilityCustomizer
version: '1.0'
main: pl.olafcio.durabilitycustomizer.DurabilityCustomizer
api-version: '1.16'
load: STARTUP
authors: [ Olafcio ]
description: Customizes (and optionally fixes) durability mechanisms.
website: https://olafcio1.github.io
commands:
  durabilitycustomizer:
    description: The main plugin command.
permissions:
  durabilitycustomizer.reload:
    description: Reloads the plugin configuration.
    default: op
